# Generated by Django 3.1 on 2020-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_auto_20200829_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=20),
        ),
    ]
